# Generated by Django 6.0 on 2026-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.IntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
