# Generated by Django 6.0 on 2026-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
