# Generated by Django 6.0 on 2026-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='jobrole',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
